import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/app/components/layouts/Header'
import Footer from '@/app/components/layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Practice Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-Jost {inter.className}'>
        <div className=' bg-black text-white text-center h-10 text-xl flex justify-center items-center'>
          <p>Black Friday Offers from as little as $10.36/m</p>
        </div>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
